export const flareTheme = {
  colors: {
    background: "#EEF6FF",
    backgroundWash: "#F3F8FF",
    surface: "#FBFDFF",
    surfaceStrong: "#FFFFFF",
    surfaceSoft: "#EAF4FF",
    surfaceMuted: "#DFECFB",
    primary: "#0B3A75",
    primaryStrong: "#062A55",
    primaryBright: "#0E5FB8",
    primaryMuted: "#D7E8FB",
    primaryMutedStrong: "#B6D2F2",
    text: "#08244A",
    textStrong: "#061A36",
    textMuted: "#3E5F86",
    textSubtle: "#6B86A6",
    border: "#BFD7F2",
    borderStrong: "#8DB7E4",
    shadow: "rgba(8, 36, 74, 0.14)",
    overlay: "rgba(8, 25, 51, 0.32)",
    successBg: "#DCEFE6",
    successText: "#1E5B43",
    neutralBg: "#DCE8F6",
    neutralText: "#35557D",
    dangerText: "#A03228",
    onPrimary: "#FFFFFF",
    onPrimaryMuted: "#EAF4FF",
  },
  shadows: {
    card: {
      shadowColor: "#08244A",
      shadowOpacity: 0.12,
      shadowRadius: 14,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      elevation: 3,
    },
    hero: {
      shadowColor: "#08244A",
      shadowOpacity: 0.16,
      shadowRadius: 18,
      shadowOffset: {
        width: 0,
        height: 10,
      },
      elevation: 4,
    },
  },
} as const;
